const openPeepsCharacterData = {
    headOptions: {
        //KEY FOR FINDING VALUE IN DICEBEAR/ VALUE WILL BE WHAT IS DISPLAYED
        afro: "Afro",
        bangs: "Bangs",
        bangs2: "Bangs 2",
        bantuKnots: "Bantu Knots",
        bear: "Bear",
        bun: "Bun",
        bun2: "Bun 2",
        buns: "Buns",
        cornrows: "Cornrows 2",
        dreads1: "Dreads 2",
        flatTop: "Flat Top",
        flatTopLong: "Flat Top Long",
        grayBun: "Gray Bun",
        grayMedium: "Gray Medium",
        grayShort: "Gray Short",
        hatBeanie: "Hat Beanie",
        hatHip: "Hat Hip",
        hijab: "Hijab",
        long: "Long",
        longAfro: "Long Afro",
        longBangs: "Long Bangs",
        longCurly: "Long Curly",
        medium1: "Medium 1",
        medium2: "Medium 2",
        medium3: "Medium 3",
        mediumBangs: "Medium Bangs 1",
        mediumBangs2: "Medium Bangs 2",
        mediumBangs3: "Medium Bangs 3",
        mediumStraight: "Medium Straight",
        mohawk: "Mohawk 1",
        mohawk2: "Mohawk 2",
        noHair1: "No Hair 1",
        noHair2: "No Hair 2",
        noHair3: "No Hair 3",
        pomp: "Pomp",
        shaved1: "Shaved 1",
        shaved2: "Shaved 2",
        shaved3: "Shaved 3",
        short1: "Short 1",
        short2: "Short 2",
        short3: "Short 3",
        short4: "Short 4",
        short5: "Short 5",
        turban: "Turban",
        twists: "Twists",
        twists2: "Twists 2",
    },

    faceOptions: {
        angryWithFang: "Angry with Fangs",
        awe: "Awe",
        blank: "Blank",
        calm: "Calm",
        cheeky: "Cheeky",
        concerned: "Concerned",
        concernedFear: "Concerned Fear",
        contempt: "contempt",
        cute: "cute",
        cyclops: "Cyclops",
        driven: "Driven",
        eatingHappy: "Eating happy",
        explaining: "Explaining",
        eyesClosed: "Eyes Closed",
        fear: "Fear",
        hectic: "Hectic",
        lovingGrin1: "Loving Grin 1",
        lovingGrin2: "Loving Grin 2",
        monster: "Monster",
        old: "Old",
        rage: "Range",
        serious: "Serious",
        smile: "Smile",
        smileBig: "Smile Big",
        smileLOL: "Smile LOL",
        smileTeethGap: "Smile Teeth Gap",
        solemn: "Solemn",
        suspicious: "Suspcious",
        tired: "Tired",
        veryAngry: "Very Angry",
    },

    facialHairOptions: {
        chin: "Chin",
        full: "Full",
        full2: "Full 2",
        full3: "Full 3",
        full4: "Full 4",
        goatee1: "Goatee 1",
        goatee2: "Goatee 2",
        moustache1: "Moustache 1",
        moustache2: "Moustache 2",
        moustache3: "Moustache 3",
        moustache4: "Moustache 4",
        moustache5: "Moustache 5",
        moustache6: "Moustache 6",
        moustache7: "Moustache 7",
        moustache8: "Moustache 8",
        moustache9: "Moustche 9",
    },

    maskOptions: {
        medicalMask: "Medical Mask",
        // respirator: "Respirator",
    },

    accessories: {
        eyepatch: "Eyepatch",
        glasses: "Glasses",
        glasses2: "Glasses 2",
        glasses3: "Glasses 3",
        glasses4: "Glasses 4",
        glasses5: "Glasses 5",
        sunglasses: "Sunglasses",
        sunglasses2: "Sunglasses 2",
    },

    skinColor: {
        variant01: "Variant 1",
        variant02: "Variant 2",
        variant03: "Variant 3",
        variant04: "Variant 4",
        variant05: "Variant 5",
    },

    clothingColor: {
        red01: "Red",
        orange01: "Orange",
        yellow01: "Yellow",
        green01: "Green",
        tail01: "Tail",
        blue01: "Blue",
        pink01: "Pink",
    },

    hairColor: {
        variant01: "Variant 1",
        variant02: "Variant 2",
        variant03: "Variant 3",
        variant04: "Variant 4",
        variant05: "Variant 5",
        variant06: "Variant 6",
        variant07: "Variant 7",
        variant08: "Variant 8",
        variant09: "Variant 9",
        variant10: "Variant 10",
    },
};

export default openPeepsCharacterData;
